application: myappudacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /unit3.*
  script: myblog.app
- url: /.*
  script: myappudacity.app
libraries:
- name: jinja2
  version: latest
